### ISSUE TITLE
Materialize collection not following guidelines!

### ISSUE THREAD

**Issue by manuthecoder** [materializecss/materialize#210]
### 1 - Why is there a border?
![image](https://user-images.githubusercontent.com/77016441/137596279-fce340bc-6c5e-4324-8be6-46b85d534fd3.png)

CSS to solve this problem: 
```css
.collection {border: none !important}
```

### 2 - Why is there a border below **every single item**? 
As per the guidelines on material.io, borders should divide topics, not every single item!

CSS to solve this problem: 
```css
.collection-item {border-bottom: none !important}
```
