### ISSUE TITLE
button with class sidenav-trigger is not shown inside of navbar

### ISSUE THREAD

**Issue by inao-cz** [materializecss/materialize#273]
## Expected Behavior
Button with class "sidenav-trigger" should be shown as other buttons

## Current Behavior
Right now, if button inside of **html > body > nav > div.nav-wrapper > ul > li** contains class "sidenav-trigger" it is not visible.

## Steps to Reproduce (for bugs)
1. Create navbar as shown in the docs
2. Create button that contains class sidenav-trigger inside of navbar
* Video: https://youtu.be/9WcvbnOPXKk

## Your Environment
* Symfony 6.1
* PHP 8.0
* Materialize 1.1.0 downloaded over CDN
* jQuery 3.6.0 - Slim, Minified

## Browser and system
* Browser Name and version:
* Version 103.0.5060.53 (Developer Build, ungoogled-chromium) (64-bit)

* Operating System and version (desktop or mobile):
* Desktop, Windows 10, Build 19043.1826

* Link to your project (if appropriate):
[https://inao.xn--6frz82g/](https://inao.xn--6frz82g/)

**Comment by LoganTann** [comment]
I see in materialize's source code that the display: none rule was deliberate

```css
// https://github.com/materializecss/materialize/blob/main/sass/components/_navbar.scss#L39
  @media #{$large-and-up} {
    a.sidenav-trigger { display: none; }
  }
```

In fact, it's used as a proper navbar feature explained here : https://materializecss.github.io/materialize/navbar.html 

As we can't change the `sidenav-trigger` class to something else, to fix this problem, add the following css rule :

```css
nav a.sidenav-trigger {
  display: initial;
}
```
